### ISSUE TITLE
[bootstrap] CentOS 6 tests fail

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-pkg-tests#120]
The CentOS 6 tests fail on both the stable and git install tests. It looks to me like this is due to some old configs where we're testing installs of 2016.11.x packages, but we should really be testing newer versions since we want to make sure Py2.7 is being tested with 2017.7. (or newer).

This issue is to track fixing these automated tests.

- [ ] stable - https://jenkins.c7.saltstack.net/job/Package%20Tests/view/Bootstrap-Script/job/develop/job/stable_install/job/cent6-stable-install/lastFailedBuild/
- [ ] git - https://jenkins.c7.saltstack.net/job/Package%20Tests/view/Bootstrap-Script/job/develop/job/git_install/job/arch-git-install/lastFailedBuild/

EDIT: Note that at the time of this posting, the actual installations work fine when manually running the bootstrap script. There's just something in the test set up here that isn't working.

**Comment by Ch3LL** [comment]
bootstrap tests are no longer handled in this repo
