### ISSUE TITLE
[bootstrap] Fedora 26 stable and git install tests fail

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-pkg-tests#122]
The Fedora 26 builds are failing on both the stable and git install tests:

- [ ] stable - https://jenkins.c7.saltstack.net/job/Package%20Tests/view/Bootstrap-Script/job/develop/job/stable_install/job/fedora26-stable-install/lastFailedBuild/
- [ ] git - https://jenkins.c7.saltstack.net/job/Package%20Tests/view/Bootstrap-Script/job/develop/job/git_install/job/fedora26-git-install/lastFailedBuild/

These tests pass just fine when running the script manually so something in the test set up isn't quite right and the python version isn't running correctly or something:

```
09:57:28               pkg_slave_minion2:
09:57:28                   qabootstraptestlinode_fedora26_python27OJZR:
09:57:28                   ----------
09:57:28                   retcode:
09:57:28                       10
09:57:28                   stderr:
09:57:28                       Warning: Permanently added '192.155.87.146' (ECDSA) to the list of known hosts.
09:57:28                       ERROR: Unable to locate appropriate python command
09:57:28                   stdout:
09:57:28                       ERROR: salt requires python 2.6 or newer on target hosts, must have same major version as origin host
```

NOTE: When attempting to troubleshoot this failure, I updated the `2016.11` value to `2017.7` in the script content config settings for the `-b` option. Didn't seem to make a difference in the test output, however.

**Comment by rallytime** [comment]
Oh, another thing to note is that if the fedora builds are running the -Z option, or using the COPR repos in their tests, this is no longer supported in the bootstrap script. Those repos haven't been updated for years, and since we are maintaining the normal fedora package builds, support for the COPR repos was removed in the most recent bootstrap release.

**Comment by Ch3LL** [comment]
bootstrap tests are no longer handled in this repo
