### ISSUE TITLE
[bootstrap] Fedora 27 stable and git install tests failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-pkg-tests#123]
This is the exact same issue as #122, but for the Fedora 27 release.

Support for Fedora 27 is new to the test run I did today, so to create the job I just copied the Fedora 26 builds and then updated the cloud profile in the jenkins configuration.

I would start with the Fedora 26 builds first, then whatever fixes that issue will likely fix this one as well.

- [ ] stable
- [ ] git

Note that the script passes just fine when run manually, so it's something in the test setup that is causing problems.

**Comment by Ch3LL** [comment]
bootstrap tests are no longer handled in this repo
