### ISSUE TITLE
[bootstrap] Ubuntu 17 stable and git builds failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-pkg-tests#124]
I don't think these have ever passed. I updated the cloud profile on the node to use the `Ubuntu 17.10` image (previously it was using `Ubutnu 17.04`, which no longer exists) but these builds are still failing and probably just need a little more :hearts:.

- [ ] git
- [ ] stable

**Comment by Ch3LL** [comment]
bootstrap tests are no longer handled in this repo
